### ISSUE TITLE
Database 

### ISSUE THREAD

**Issue by zeyzofc** [whiskey34/learning-payment-gateway#1]
Where database

**Comment by whiskey34** [comment]
Sorry im not upload my database in my repo for this project

**Comment by whiskey34** [comment]
If you still want my db i could give you via email

**Comment by whiskey34** [comment]
here i already upload to the repo for you now you can download it

**Comment by zeyzofc** [comment]
Thanks

**Comment by zeyzofc** [comment]
Bro database eror

**Comment by whiskey34** [comment]
hmm....  okay let me see my database again

**Comment by whiskey34** [comment]
what kind of error you get of the DB ?

**Comment by zeyzofc** [comment]
USE `porj4351_shopping_db`;
MySQL menyatakan: Dokumentasi

#1044 - Access denied for user 'cpses_yomv6icy3q'@'localhost' to database 'porj4351_shopping_db'


&& And my hosting CSS does not display version php 8.0 If I switch to 8.2 it throws an error

**Comment by whiskey34** [comment]
okay hold on

**Comment by whiskey34** [comment]
i see its the name i use i forgot to erase porj4351_ on the name of my DB i'll upload newer for you

**Comment by whiskey34** [comment]
hey i'm uploaded new DB now you can try to import in your DB and let me know if you have any trouble from my project.

**Comment by zeyzofc** [comment]
I try it

**Comment by zeyzofc** [comment]
I get error when import , replace shoping_db name ,my database yowhzbpz_zyzgames

Error Static data: 1 error was found in the analysis. Unknown statement type. (near "DEFAULT" at position 131) SQL Query: Copy CREATE DATABASE /*!32312 IF NOT EXISTS*/`yowhzbpz_zyzgames` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */; MySQL states: Documentation #1273 - Unknown collation: 'utf8mb4_0900_ai_ci'

**Comment by whiskey34** [comment]
hmm okay so thats looks like from the collation '**utf8mb4_0900_ai_ci**' from my DB

**Comment by whiskey34** [comment]
okay i already finish fixing the collation and changes to utf8mb4_general_ci and this issue : CREATE DATABASE /!32312 IF NOT EXISTS/yowhzbpz_zyzgames /*!40100

**Comment by whiskey34** [comment]
let me know if you success or got more error

**Comment by whiskey34** [comment]
you can do contribute in my project to help me fixing any bugs if you could thx.

**Comment by zeyzofc** [comment]
Problem getting 
1 error was found in the analysis. Unknown statement type. (near "DEFAULT" at position 107) SQL Query: Copy CREATE DATABASE `shoping_db` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */; MySQL states: Documentation #1044 - Access denied for user 'id20853729_zeyz'@'%' to database 'shoping_db

**Comment by whiskey34** [comment]
which mysql version are you ?

**Comment by whiskey34** [comment]
to fix this issue :  Access denied for user 'id20853729_zeyz'@'%' to database 'shoping_db. you should add GRANT ALL PRIVILEGES ON *.* TO 'id20853729_zeyz'@'%'; in .sql file 

you can edit .sql file in your VS Code or notepad++ or any code editor you have.

**Comment by whiskey34** [comment]
and i already fix this issue : (near "DEFAULT" at position 107) SQL Query: Copy CREATE DATABASE shoping_db /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci / /!80016 DEFAULT ENCRYPTION='N' */;

**Comment by whiskey34** [comment]
you could try it again

**Comment by whiskey34** [comment]
so its working or not ?

**Comment by zeyzofc** [comment]
Working, The view 
![IMG_20240428_182721](https://github.com/whiskey34/learning-payment-gateway/assets/144014471/228aa1ae-a8ed-4461-9e2b-1c344b1d2d03)

**Comment by whiskey34** [comment]
you should use php version 7.8 dont use 8.0 or higher because it will get error

**Comment by whiskey34** [comment]
just try that if you got error again or working fined tell me 😊

**Comment by zeyzofc** [comment]
> sebaiknya gunakan php versi 7.8 jangan gunakan 8.0 atau lebih tinggi karena akan error

I've used 7.4 successfully but the CSS doesn't load

**Comment by whiskey34** [comment]
you should tweaking little bit for the css for the link href="..."

**Comment by zeyzofc** [comment]
> you should tweaking little bit for the css for the link href="..."

Where?

**Comment by whiskey34** [comment]
hmm can i see what kind of error of your css ?

**Comment by whiskey34** [comment]
i put in folder views/template.php

**Comment by zeyzofc** [comment]
![Uploading IMG_20240429_191246.jpg…]()

**Comment by whiskey34** [comment]
your image was broken

**Comment by whiskey34** [comment]
can you send again ?

**Comment by zeyzofc** [comment]
![Uploading IMG_20240429_191246.jpg…]()

**Comment by zeyzofc** [comment]
Ok

**Comment by zeyzofc** [comment]
![Screenshot_2024-04-29-19-08-04-363_com android chrome](https://github.com/whiskey34/learning-payment-gateway/assets/144014471/8d1aaad9-7a13-4d4e-b3ad-2b63b3206070)

**Comment by whiskey34** [comment]
hmm let me check that

**Comment by whiskey34** [comment]
its interesting it's look like you already deploy it to the hosting try so maybe try ask chatgpt for this one though because i've never get this issues before
